pull_request_rules:
  - name: Add test label
    conditions:
      - author = Aman001122
    actions:
      label:
        add:
          - mergify-test
queue_rules:
  - name: test-queue
    queue_conditions:
      - author = Aman001122
